### ISSUE TITLE
Benefits over more traditional tangling

### ISSUE THREAD

**Issue by mankoff** [dantecatalfamo/ox-ssh#1]
I think this looks neat and I'm happy to see it on Melpa, but I'm trying to understand the benefits over my existing workflow. Currently I manage my `.ssh/config` with all my dotfiles in a `.dotfiles.org`. The ssh section contains this:

```
* Shell
** ssh
:PROPERTIES:
:header-args:conf: :tangle ~/.ssh/config :mkdirp .ssh
:END:

*** Global
These apply to all hosts

#+BEGIN_SRC conf
Host *
     AddKeysToAgent yes
     ForwardX11 no
#+END_SRC

*** Host foo
Some comments about this host, etc.

#+BEGIN_SRC conf
Host foo
     User bar
     Hostname some.computer.com
     PermitLocalCommand yes
     LocalCommand konsoleprofile ColorScheme=ComputerDotComColorScheme
#+END_SRC

*** Hosts at bar
...

```

The major advantage of `PROPERTY` drawers is that they should be inherited by children (I think?) but that doesn't seem to be the case in your export. I would expect that `vm-1` and `vm-2` have `SSH_PORT: 2222` set because they are children of `proxmox`.

**Comment by dantecatalfamo** [comment]
I know tags are inherited by children, but I don't think properties are. I prefer using properties for something like this because I can use things like sparse tree for finding say all clients with agent forwarding, and completion when filling out the fields. I actually use the completion a lot, like when I'm assigning a new static IP, helm will show me the list of IPs already in use while filling the properties out. I like how the properties are hidden, since when managing the list of hosts, adding details and info, I rarely want to edit things like the IP address or SSH port, so this keeps them out of the way. It also ensures the export is uniform.

**Comment by mankoff** [comment]
Makes sense. Header-arguments as tags are inherited with tangling, so I thought these might too. I think that would make this powerful for multiple hosts within projects or sub-hosts within a domain. Anyway, very nice!
